/**
 * Curated LaTeX vocabulary for autocompletion. Snippet syntax follows
 * @codemirror/autocomplete: #{name} marks a tab stop.
 */

export interface CommandSpec {
  /** Command name without backslash. */
  name: string;
  /** Snippet inserted after the backslash; defaults to the name. */
  snippet?: string;
  detail?: string;
}

const arg = (name: string, detail?: string, argName = ''): CommandSpec => ({
  name,
  snippet: `${name}{#{${argName}}}`,
  ...(detail ? { detail } : {}),
});
const plain = (name: string, detail?: string): CommandSpec => ({ name, ...(detail ? { detail } : {}) });

export const COMMANDS: CommandSpec[] = [
  // Document structure
  { name: 'documentclass', snippet: 'documentclass[#{options}]{#{article}}', detail: 'document class' },
  { name: 'usepackage', snippet: 'usepackage{#{}}', detail: 'load package' },
  arg('part', 'sectioning'),
  arg('chapter', 'sectioning'),
  arg('section', 'sectioning'),
  arg('subsection', 'sectioning'),
  arg('subsubsection', 'sectioning'),
  arg('paragraph', 'sectioning'),
  arg('subparagraph', 'sectioning'),
  arg('title'),
  arg('author'),
  arg('date'),
  plain('maketitle'),
  plain('tableofcontents'),
  plain('listoffigures'),
  plain('listoftables'),
  plain('appendix'),
  plain('frontmatter'),
  plain('mainmatter'),
  plain('backmatter'),
  arg('input', 'include file', 'file'),
  arg('include', 'include file (new page)', 'file'),
  arg('includeonly', undefined, 'files'),
  // References
  arg('label', 'label'),
  arg('ref', 'reference', 'label'),
  arg('eqref', 'equation reference', 'label'),
  arg('pageref', 'page reference', 'label'),
  arg('autoref', 'hyperref reference', 'label'),
  arg('cref', 'cleveref reference', 'label'),
  arg('Cref', 'cleveref reference', 'label'),
  arg('nameref', 'reference by name', 'label'),
  arg('cite', 'citation', 'key'),
  { name: 'citep', snippet: 'citep{#{key}}', detail: 'natbib' },
  { name: 'citet', snippet: 'citet{#{key}}', detail: 'natbib' },
  { name: 'parencite', snippet: 'parencite{#{key}}', detail: 'biblatex' },
  { name: 'textcite', snippet: 'textcite{#{key}}', detail: 'biblatex' },
  { name: 'autocite', snippet: 'autocite{#{key}}', detail: 'biblatex' },
  arg('nocite', undefined, 'key'),
  arg('bibliography', 'BibTeX database', 'file'),
  arg('bibliographystyle', 'BibTeX style', 'plain'),
  arg('addbibresource', 'biblatex database', 'file.bib'),
  plain('printbibliography', 'biblatex'),
  arg('footnote'),
  arg('footnotetext'),
  { name: 'href', snippet: 'href{#{url}}{#{text}}', detail: 'hyperlink' },
  arg('url'),
  // Text formatting
  arg('textbf', 'bold'),
  arg('textit', 'italic'),
  arg('emph', 'emphasis'),
  arg('underline'),
  arg('texttt', 'monospace'),
  arg('textsc', 'small caps'),
  arg('textsf', 'sans serif'),
  arg('textrm', 'roman'),
  arg('textsuperscript'),
  arg('textsubscript'),
  arg('mbox'),
  arg('text', 'text in math'),
  plain('tiny'),
  plain('scriptsize'),
  plain('footnotesize'),
  plain('small'),
  plain('normalsize'),
  plain('large'),
  plain('Large'),
  plain('LARGE'),
  plain('huge'),
  plain('Huge'),
  plain('centering'),
  plain('raggedright'),
  plain('raggedleft'),
  plain('noindent'),
  plain('newline'),
  plain('linebreak'),
  plain('newpage'),
  plain('clearpage'),
  plain('cleardoublepage'),
  plain('pagebreak'),
  { name: 'vspace', snippet: 'vspace{#{1em}}' },
  { name: 'hspace', snippet: 'hspace{#{1em}}' },
  plain('vfill'),
  plain('hfill'),
  plain('smallskip'),
  plain('medskip'),
  plain('bigskip'),
  plain('item', 'list item'),
  plain('today'),
  plain('LaTeX'),
  plain('TeX'),
  plain('ldots'),
  plain('dots'),
  // Floats and graphics
  { name: 'includegraphics', snippet: 'includegraphics[width=#{\\linewidth}]{#{file}}', detail: 'graphicx' },
  arg('caption'),
  arg('captionof', undefined, 'figure'),
  plain('hline'),
  plain('toprule'),
  plain('midrule'),
  plain('bottomrule'),
  { name: 'multicolumn', snippet: 'multicolumn{#{2}}{#{c}}{#{text}}' },
  { name: 'multirow', snippet: 'multirow{#{2}}{*}{#{text}}' },
  // Definitions
  { name: 'newcommand', snippet: 'newcommand{\\#{name}}[#{1}]{#{definition}}', detail: 'define macro' },
  { name: 'renewcommand', snippet: 'renewcommand{\\#{name}}{#{definition}}' },
  { name: 'newenvironment', snippet: 'newenvironment{#{name}}{#{begin}}{#{end}}' },
  { name: 'DeclareMathOperator', snippet: 'DeclareMathOperator{\\#{name}}{#{text}}' },
  { name: 'newtheorem', snippet: 'newtheorem{#{theorem}}{#{Theorem}}' },
  { name: 'setlength', snippet: 'setlength{\\#{parindent}}{#{0pt}}' },
  { name: 'setcounter', snippet: 'setcounter{#{counter}}{#{0}}' },
  // Math
  { name: 'frac', snippet: 'frac{#{num}}{#{den}}', detail: 'fraction' },
  { name: 'dfrac', snippet: 'dfrac{#{num}}{#{den}}' },
  { name: 'sqrt', snippet: 'sqrt{#{x}}', detail: 'square root' },
  { name: 'sum', snippet: 'sum_{#{i=1}}^{#{n}}' },
  { name: 'prod', snippet: 'prod_{#{i=1}}^{#{n}}' },
  { name: 'int', snippet: 'int_{#{a}}^{#{b}}' },
  { name: 'lim', snippet: 'lim_{#{x \\to \\infty}}' },
  arg('mathbf'),
  arg('mathrm'),
  arg('mathit'),
  arg('mathcal'),
  arg('mathbb'),
  arg('mathfrak'),
  arg('mathsf'),
  arg('operatorname'),
  arg('hat'),
  arg('bar'),
  arg('tilde'),
  arg('vec'),
  arg('dot'),
  arg('overline'),
  arg('underbrace'),
  arg('overbrace'),
  plain('left'),
  plain('right'),
  plain('cdot'),
  plain('cdots'),
  plain('times'),
  plain('infty'),
  plain('partial'),
  plain('nabla'),
  plain('forall'),
  plain('exists'),
  plain('in'),
  plain('notin'),
  plain('subset'),
  plain('subseteq'),
  plain('cup'),
  plain('cap'),
  plain('setminus'),
  plain('emptyset'),
  plain('leq'),
  plain('geq'),
  plain('neq'),
  plain('approx'),
  plain('equiv'),
  plain('sim'),
  plain('propto'),
  plain('pm'),
  plain('mp'),
  plain('to'),
  plain('mapsto'),
  plain('rightarrow'),
  plain('leftarrow'),
  plain('Rightarrow'),
  plain('Leftarrow'),
  plain('iff'),
  plain('implies'),
  plain('quad'),
  plain('qquad'),
  ...[
    'alpha',
    'beta',
    'gamma',
    'delta',
    'epsilon',
    'varepsilon',
    'zeta',
    'eta',
    'theta',
    'vartheta',
    'iota',
    'kappa',
    'lambda',
    'mu',
    'nu',
    'xi',
    'pi',
    'rho',
    'sigma',
    'tau',
    'upsilon',
    'phi',
    'varphi',
    'chi',
    'psi',
    'omega',
    'Gamma',
    'Delta',
    'Theta',
    'Lambda',
    'Xi',
    'Pi',
    'Sigma',
    'Upsilon',
    'Phi',
    'Psi',
    'Omega',
  ].map((g) => plain(g, 'greek')),
  ...['sin', 'cos', 'tan', 'log', 'ln', 'exp', 'max', 'min', 'sup', 'inf', 'det', 'dim'].map((f) =>
    plain(f, 'math operator'),
  ),
];

export const ENVIRONMENTS: string[] = [
  'document',
  'abstract',
  'itemize',
  'enumerate',
  'description',
  'figure',
  'figure*',
  'table',
  'table*',
  'tabular',
  'tabularx',
  'longtable',
  'center',
  'flushleft',
  'flushright',
  'quote',
  'quotation',
  'verse',
  'verbatim',
  'minipage',
  'equation',
  'equation*',
  'align',
  'align*',
  'gather',
  'gather*',
  'multline',
  'multline*',
  'split',
  'cases',
  'matrix',
  'pmatrix',
  'bmatrix',
  'vmatrix',
  'array',
  'subequations',
  'theorem',
  'lemma',
  'proof',
  'definition',
  'corollary',
  'proposition',
  'remark',
  'example',
  'frame',
  'block',
  'columns',
  'column',
  'thebibliography',
  'tikzpicture',
  'subfigure',
  'wrapfigure',
  'lstlisting',
  'appendices',
  'titlepage',
];

/** Snippet body for an environment (content placed between begin and end). */
export function environmentBody(env: string): string {
  if (['itemize', 'enumerate'].includes(env)) return '\t\\item #{}';
  if (env === 'description') return '\t\\item[#{term}] #{}';
  if (env === 'figure' || env === 'figure*') {
    return '\t\\centering\n\t\\includegraphics[width=\\linewidth]{#{file}}\n\t\\caption{#{caption}}\n\t\\label{fig:#{label}}';
  }
  if (env === 'table' || env === 'table*') {
    return '\t\\centering\n\t\\begin{tabular}{#{lll}}\n\t\t#{}\n\t\\end{tabular}\n\t\\caption{#{caption}}\n\t\\label{tab:#{label}}';
  }
  if (env === 'tabular') return '\t#{}';
  return '\t#{}';
}

export const PACKAGES: string[] = [
  'amsmath',
  'amssymb',
  'amsthm',
  'mathtools',
  'graphicx',
  'xcolor',
  'hyperref',
  'cleveref',
  'geometry',
  'fontenc',
  'inputenc',
  'babel',
  'csquotes',
  'biblatex',
  'natbib',
  'booktabs',
  'tabularx',
  'longtable',
  'multirow',
  'array',
  'caption',
  'subcaption',
  'float',
  'wrapfig',
  'tikz',
  'pgfplots',
  'listings',
  'enumitem',
  'fancyhdr',
  'titlesec',
  'microtype',
  'siunitx',
  'lmodern',
  'fontspec',
  'unicode-math',
  'setspace',
  'parskip',
  'url',
  'xspace',
  'todonotes',
  'algorithm2e',
  'algorithmicx',
  'algpseudocode',
  'physics',
  'bm',
  'mhchem',
  'chemfig',
  'lipsum',
  'blindtext',
  'appendix',
  'glossaries',
  'acronym',
  'makeidx',
  'imakeidx',
  'multicol',
  'ragged2e',
  'xparse',
  'etoolbox',
  'calc',
  'ifthen',
  'pdfpages',
  'standalone',
  'beamer',
  'tcolorbox',
  'mdframed',
  'framed',
  'soul',
  'ulem',
  'textcomp',
];
